# Generated by Django 4.2.28 on 2026-03-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='상호명')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('address', models.CharField(max_length=300, verbose_name='주소')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='전화번호')),
                ('business_hours', models.TextField(blank=True, verbose_name='영업시간')),
                ('avg_rating', models.FloatField(default=0.0, verbose_name='평균 평점')),
                ('rating_count', models.IntegerField(default=0, verbose_name='평가 수')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='태그')),
                ('recommended_for', models.CharField(blank=True, max_length=200, verbose_name='추천 동행유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '음식점',
                'verbose_name_plural': '음식점 목록',
                'ordering': ['-avg_rating', '-rating_count'],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='평점')),
                ('comment', models.TextField(blank=True, verbose_name='후기')),
                ('age_group', models.CharField(blank=True, max_length=20, verbose_name='연령대')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='성별')),
                ('companion_type', models.CharField(blank=True, max_length=20, verbose_name='동행유형')),
                ('companion_count', models.IntegerField(default=1, verbose_name='동행자 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='onsik.restaurant', verbose_name='음식점')),
            ],
            options={
                'verbose_name': '사용자 평가',
                'verbose_name_plural': '사용자 평가 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
