# Generated by Django 4.2.28 on 2026-03-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(blank=True, max_length=30, verbose_name='대표 연령대')),
                ('age_gender_counts', models.JSONField(default=dict, verbose_name='연령대별 성별 인원')),
                ('companion_type', models.CharField(blank=True, max_length=20, verbose_name='동행유형')),
                ('companion_count', models.IntegerField(default=1, verbose_name='동행자 수')),
                ('transport', models.CharField(blank=True, max_length=20, verbose_name='이동수단')),
                ('categories', models.JSONField(default=list, verbose_name='선택 카테고리')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='기준 위치')),
                ('special_prompt_shown', models.BooleanField(default=False, verbose_name='어린이/노인 맞춤 확인창 노출 여부')),
                ('flow_choice', models.CharField(blank=True, max_length=10, verbose_name='추천 흐름 선택')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '사용자 선택 로그',
                'verbose_name_plural': '사용자 선택 로그 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
